FROM ubuntu

WORKDIR /app

ENV FLASK_ENV=production
ENV FLASK_APP=server.py

RUN apt-get update -y && apt-get install -y python3-pip python3-dev ffmpeg libsm6 libxext6

COPY requirements.txt ./
RUN pip install -r requirements.txt
RUN pip install gunicorn

EXPOSE 5000

COPY . .

CMD ["gunicorn", "-b", ":5000", "server:app"]
